### ISSUE TITLE
Search whole sentence

### ISSUE THREAD

**Issue by quazar-omega** [pancevac/firefox-ytsc-extension#47]
Is it possible to search the sentence as it is input?
For example, if I type "how to" currently I get results that contain the two words "how" and "to" placed anywhere in the comment string, I'd like to be able to search for the whole thing, i.e. find the instances of the substring "how to" inside the comment

**Comment by pancevac** [comment]
So far as my knowledge go, Youtube API [docs](https://developers.google.com/youtube/v3/docs/commentThreads/list) field "searchTerms" does not support wildcards/regex patterns.
I'm brainstorming now but I think technically it could be done on extension side by ignoring sent wildcard symbols and filtering response results by those symbols.
You are welcomed to make any PR if you have an idea how this could be implemented.
Thanks
