### ISSUE TITLE
Suggestion--I like controversies so want to view shadowbanned comments listing.

### ISSUE THREAD

**Issue by oldspammer** [pancevac/firefox-ytsc-extension#48]
I like free speech a lot, but the Google AI works against certain people expressing their strongly, rightfully justified viewpoints.

The old politically motivated fad is "cancel culture."

Right now there are two levels of "cancel culture" for YouTube--the Google AI detects that a phrase in your remark is "NOT politically correct" and within a minute or less deletes it, OR, there is a grey area, and your remark is shadowbanned so that only you can see the comment and no one else can see it unless they Sort comments by Newest First, then scroll around to find it.

To more quickly know if your comment was censored outright, or shadow banned, the plug-in application should have a "REFRESH" for the latest comments rather than re-read 50 thousand comments from scratch again displaying slowly the progress by printing comment quantity read from the YouTube API one by one. You would then do a search for your username in the comments, and should your latest remarks not show up, then suspect the worse and hope for the best.

One can estimate the number of shadow bannings by the difference between the plug-in app's total comment count differing from the YouTube screen's comment count being a few percent less or so.

**Comment by pancevac** [comment]
I'm not sure if I understood what is your proposal here but this extension is just using YouTube API for fetching comment results.
All searching is done by YouTube, only thing that could be done on extension side is "filtering" of already returned results from Youtube API.
As always, feel free to propose PR with solution and I will gladly take it into consideration.
